HW3
IKFor/HomeWork-PRJCTR pull request #4
Opened 2023-06-21 19:26 UTC by IKFor

2023-06-23 13:00 UTC, myroslav-kolomiiets requested changes

2023-06-23 13:00 UTC, myroslav-kolomiiets commented on HW3.js
> +function addThemAll(...args) {
Вірно.

Просто як варіант, ще зручно тут використати reduce

2023-06-23 13:00 UTC, myroslav-kolomiiets commented on HW3.js
> +    }
```suggestion
function multiply(a) {
    return function (b) {
        return a *= b;
    }
```

Об'являти змінну, що використовується в одному місці, не має сенсу, можна спростити

2023-06-23 13:00 UTC, myroslav-kolomiiets commented on HW3.js
> +    }
Або взагалі - `const multiply = (a) => (b) => a *= b;`

Але це вже як приклад.

2023-06-23 13:00 UTC, myroslav-kolomiiets commented on HW3.js
> +function byProperty(property, direction) {
function declaration, звісно, дозволяє нам використовувати функції до їх об'явлення, але це поганий стиль, рекомендую тут, і надалі, спочатку об'являти функцію, потім її використовувати

2023-06-23 13:00 UTC, myroslav-kolomiiets commented on HW3.js
> +console.log(movies.sort(byProperty("releaseYear", "<"))); // виведе масив фільмів посортованих по року випуску, від старішого до новішого
Не вірна обробка параметра direction, не відповідає умові, також, не змінюйте тести відносто завдання

2023-06-23 13:00 UTC, myroslav-kolomiiets commented on HW3.js
> +    setTimeout(detonatorTimer1, 1000, delay);
Тут не мається на увазі рекурсивний виклик, тут має бути вкладений setTimeout в інший setTimeout

2023-06-23 13:00 UTC, myroslav-kolomiiets commented on HW3.js
> +    function timer () {
Те ж саме про порядок об'явлення функцій, краще опишіть логіку всередині setInterval

2023-06-23 16:17 UTC, IKFor commented on HW3.js
> +function byProperty(property, direction) {
@myroslav-kolomiiets Зрозумів, я просто скопіював цю частину з дз тому так і залишив

2023-06-24 13:59 UTC, myroslav-kolomiiets commented on HW3.js
> +function byProperty(property, direction) {
Так, я там виправив вже, щоб не вводило в оману

2023-06-24 14:07 UTC, myroslav-kolomiiets approved these changes

2023-06-28 11:37 UTC, merged